name: Build and Deploy JupyterLite Site

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build-lite:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use a recent Python version compatible with JupyterLite

    - name: Install JupyterLite and jupyter-repo2jupyterlite
      # Install the core JupyterLite package and the repo2jupyterlite tool
      run: |
        pip install jupyterlite
        pip install jupyter-repo2jupyterlite

    - name: Create jupyter_lite_config.json (or ensure it's in place)
      # This step ensures the config file exists in the current working directory (repo root)
      # You can replace this with a 'COPY' if you prefer to keep it in your repo
      # For this specific issue, we'll use 'extra_ignore_contents' as suggested by the error
      run: |
        echo '{
          "LiteBuildConfig": {
            "extra_ignore_contents": [
              "/.devcontainer",
              "/.github",
              "/.env"
            ]
          }
        }' > jupyter_lite_config.json


    - name: Build JupyterLite site
      # Run jupyter-repo2jupyterlite to prepare contents, then jupyter lite build
      # The --config jupyter_lite_config.json ensures your config is used.
      # The --contents . tells jupyter lite build to process the current directory's contents.
      run: |
        jupyter-repo2jupyterlite convert --output-dir _output --config jupyter_lite_config.json
        jupyter lite build --output-dir _output --config jupyter_lite_config.json --contents .

    - name: Upload generated site artifact
      uses: actions/upload-pages-artifact@v3
      with:
          path: ./_output # JupyterLite builds to _output by default